export const UPDATE_PLAYER  = 'UPDATE_PLAYER';

export const ADD_ORDER_OF_BATTLE = 'ADD_ORDER_OF_BATTLE';
export const DELETE_ORDER_OF_BATTLE = 'DELETE_ORDER_OF_BATTLE';
export const LOAD_CURRENT_ORDER_OF_BATTLE = 'LOAD_CURRENT_ORDER_OF_BATTLE';
export const SAVE_CURRENT_ORDER_OF_BATTLE = 'SAVE_CURRENT_ORDER_OF_BATTLE';
