export const UPDATE_PLAYER  = 'UPDATE_PLAYER';

export const SET_ORDERS_OF_BATTLE = 'SET_ORDERS_OF_BATTLE';

export const SET_CURRENT_ORDER_OF_BATTLE = 'SET_CURRENT_ORDER_OF_BATTLE';
export const SET_CRUSADE_CARDS = 'SET_CRUSADE_CARDS';

export const SET_CURRENT_CRUSADE_CARD = 'SET_CURRENT_CRUSADE_CARD';
