export enum AccountActions {
    CREATE_ACCOUNT = 'CREATE_ACCOUNT',
    UPDATE_ACCOUNT = 'UPDATE_ACCOUNT',
    DELETE_ACCOUNT = 'DELETE_ACCOUNT',
    SELECT_ACCOUNT = 'SELECT_ACCOUNT'
}

export enum OrderOfBattleActions {
    CREATE_ORDER_OF_BATTLE = 'CREATE_ORDER_OF_BATTLE',
    UPDATE_ORDER_OF_BATTLE = 'UPDATE_ORDER_OF_BATTLE',
    DELETE_ORDER_OF_BATTLE = 'DELETE_ORDER_OF_BATTLE',
    SELECT_ORDER_OF_BATTLE = 'SELECT_ORDER_OF_BATTLE'
}

export enum CrusadeCardActions {
    CREATE_CRUSADE_CARD = 'CREATE_CRUSADE_CARD',
    UPDATE_CRUSADE_CARD = 'UPDATE_CRUSADE_CARD',
    DELETE_CRUSADE_CARD = 'DELETE_CRUSADE_CARD',
    SELECT_CRUSADE_CARD = 'SELECT_CRUSADE_CARD'
}
