export enum AvailableActions {
    CREATE_ACCOUNT = 'CREATE_ACCOUNT',
    UPDATE_ACCOUNT = 'UPDATE_ACCOUNT',
    DELETE_ACCOUNT = 'DELETE_ACCOUNT',
    SELECT_ACCOUNT = 'SELECT_ACCOUNT',
    CREATE_ORDER_OF_BATTLE = 'CREATE_ORDER_OF_BATTLE',
    UPDATE_ORDER_OF_BATTLE = 'UPDATE_ORDER_OF_BATTLE',
    DELETE_ORDER_OF_BATTLE = 'DELETE_ORDER_OF_BATTLE',
    SELECT_ORDER_OF_BATTLE = 'SELECT_ORDER_OF_BATTLE',
    CREATE_CRUSADE_CARD = 'CREATE_CRUSADE_CARD',
    UPDATE_CRUSADE_CARD = 'UPDATE_CRUSADE_CARD',
    DELETE_CRUSADE_CARD = 'DELETE_CRUSADE_CARD',
    SELECT_CRUSADE_CARD = 'SELECT_CRUSADE_CARD',
    CREATE_BATTLE_RESULT = 'CREATE_BATTLE_RESULT',
    UPDATE_BATTLE_RESULT = 'UPDATE_BATTLE_RESULT',
    DELETE_BATTLE_RESULT = 'DELETE_BATTLE_RESULT',
    SELECT_BATTLE_RESULT = 'SELECT_BATTLE_RESULT',
    SET_BATTLE_IN_PRGRESS = 'SET_BATTLE_IN_PROGRESS'
}

export type OrderOfBattleActions =
    AvailableActions.CREATE_ORDER_OF_BATTLE |
    AvailableActions.DELETE_ORDER_OF_BATTLE |
    AvailableActions.SELECT_ORDER_OF_BATTLE |
    AvailableActions.UPDATE_ORDER_OF_BATTLE

export type CrusadeCardActions =
    AvailableActions.CREATE_CRUSADE_CARD |
    AvailableActions.DELETE_CRUSADE_CARD |
    AvailableActions.SELECT_CRUSADE_CARD |
    AvailableActions.UPDATE_CRUSADE_CARD

export type AccountActions =
    AvailableActions.CREATE_ACCOUNT |
    AvailableActions.DELETE_ACCOUNT |
    AvailableActions.SELECT_ACCOUNT |
    AvailableActions.UPDATE_ACCOUNT

export type BattleResultActions =
    AvailableActions.CREATE_BATTLE_RESULT |
    AvailableActions.DELETE_BATTLE_RESULT |
    AvailableActions.SELECT_BATTLE_RESULT |
    AvailableActions.UPDATE_BATTLE_RESULT

export type BattleInProgressActions =
    AvailableActions.SET_BATTLE_IN_PRGRESS
